version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql

  backend:
    image: php:latest
    restart: always
    volumes:
      - ../:/var/www/html
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html/public"]
